import { Serie } from "./serie.js";
export var data = [
    new Serie(1, "Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "https://www.amc.com/shows/breaking-bad", "https://cdn.glitch.global/4ec0d6d6-c05b-4df7-a8f2-f4b63cd9d8ed/1.jpg?v=1681518092811"),
    new Serie(2, "Orange Is the New Black", "Netflix", 6, "Convicted of transporting drug money to an ex-girlfriend ten years ago, normally good citizen Piper Chapman is sentenced to a year and a half behind bars and faces the reality of how prison can change your life.", "https://www.netflix.com/co/title/70242311", "https://cdn.glitch.global/4ec0d6d6-c05b-4df7-a8f2-f4b63cd9d8ed/2.jpg?v=1681518070837"),
    new Serie(3, "Game of Thrones", "HBO", 7, "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.", "https://www.hbo.com/game-of-thrones", "https://cdn.glitch.global/4ec0d6d6-c05b-4df7-a8f2-f4b63cd9d8ed/3.jpg?v=1681517891801"),
    new Serie(4, "The Big Bang Theory", "CBS", 12, "A woman, who moves into the apartment across the street from two brilliant but socially awkward physicists, shows them how little she knows about life outside the laboratory.", "https://www.cbs.com/shows/big_bang_theory/about/", "https://cdn.glitch.global/4ec0d6d6-c05b-4df7-a8f2-f4b63cd9d8ed/4.jpg?v=1681517854175"),
    new Serie(5, "Sherlock", "BBC", 4, "The famous detective Sherlock Holmes and his partner Dr. Watson solve crimes in 21st century London.", "https://www.bbc.co.uk/programmes/b018ttws", "https://cdn.glitch.global/4ec0d6d6-c05b-4df7-a8f2-f4b63cd9d8ed/5.jpg?v=1681517787087"),
    new Serie(6, "A Very English Scandal", "BBC", 2, "In 1979, the leader of the British Liberal Party is accused of plotting to murder his ex-lover, another man, and must stand trial.", "https://www.bbc.co.uk/programmes/p065smy4", "https://cdn.glitch.global/4ec0d6d6-c05b-4df7-a8f2-f4b63cd9d8ed/6.jpg?v=1681517754855")
];
